version: 2
jobs:
  install-dependencies:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/kevchang14/kevchang14-website-vue
    steps:
      - checkout
      - attach_workspace:
          at: ~/kevchang14/kevchang14-website-vue
      - run:
          name: "Install s3deploy"
          command: curl -L https://github.com/bep/s3deploy/releases/download/v2.3.2/s3deploy_2.3.2_Linux-64bit.tar.gz | tar xvz
      - persist_to_workspace:
          root: .
          paths:
            - s3deploy

  build:
    docker:
      - image: circleci/node:8.11.2
    parallelism: 1
    working_directory: ~/kevchang14/kevchang14-website-vue
    steps:
      - checkout
      - attach_workspace:
          at: ~/kevchang14/kevchang14-website-vue
      - restore_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run: npm run build
      - persist_to_workspace:
          root: .
          paths: dist

  deploy:
    docker:
      - image: circleci/golang:1.9.6
    parallelism: 1
    working_directory: ~/kevchang14/kevchang14-website-vue
    steps:
      - checkout
      - attach_workspace:
          at: ~/kevchang14/kevchang14-website-vue
      - restore_cache:
          key: v1-pkg-cache
      - run: go get -u -v github.com/bep/s3deploy
      - save_cache:
          key: v1-pkg-cache
          paths:
            - /go/pkg
      - run:
          name: Deploy to S3
          command: |
            s3deploy -source=dist/ -region=ap-southeast-1 -bucket=personal-test-website-static-content

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - install-dependencies
      - build
      - deploy:
          requires:
            - build
            - install-dependencies
          filters:
            branches:
              only: master